INSERT INTO users (name, email, location)
VALUES
('John Smith', 'john.smith@example.com', 'New York'),
('Jane Doe', 'jane.doe@example.com', 'Los Angeles'),
('Bob Johnson', 'bob.johnson@example.com', 'Chicago'),
('Sara Lee', 'sara.lee@example.com', 'San Francisco'),
('Tom Jones', 'tom.jones@example.com', 'Seattle'),
('Emily Brown', 'emily.brown@example.com', 'Houston'),
('Mike Davis', 'mike.davis@example.com', 'Miami'),
('Hannah Wilson', 'hannah.wilson@example.com', 'Boston'),
('David Johnson', 'david.johnson@example.com', 'Washington DC'),
('Karen Smith', 'karen.smith@example.com', 'Dallas'),
('Mark Wilson', 'mark.wilson@example.com', 'San Diego'),
('Amy Lee', 'amy.lee@example.com', 'Austin'),
('Kevin Davis', 'kevin.davis@example.com', 'Atlanta'),
('Lisa Chen', 'lisa.chen@example.com', 'San Jose'),
('Steve Brown', 'steve.brown@example.com', 'Phoenix'),
('Jenny Kim', 'jenny.kim@example.com', 'Portland'),
('Brian Johnson', 'brian.johnson@example.com', 'Denver'),
('Rachel Lee', 'rachel.lee@example.com', 'Minneapolis'),
('Eric Wilson', 'eric.wilson@example.com', 'Philadelphia'),
('Katie Davis', 'katie.davis@example.com', 'Charlotte'),
('Jack Smith', 'jack.smith@example.com', 'Nashville'),
('Linda Chen', 'linda.chen@example.com', 'New Orleans'),
('Sam Johnson', 'sam.johnson@example.com', 'Las Vegas'),
('Megan Brown', 'megan.brown@example.com', 'Salt Lake City'),
('Chris Lee', 'chris.lee@example.com', 'Kansas City'),
('Stephanie Wilson', 'stephanie.wilson@example.com', 'Oklahoma City'),
('Andrew Davis', 'andrew.davis@example.com', 'Orlando'),
('Julia Kim', 'julia.kim@example.com', 'Tampa'),
('Patrick Johnson', 'patrick.johnson@example.com', 'Raleigh'),
('Melissa Smith', 'melissa.smith@example.com', 'Cincinnati'),
('Scott Brown', 'scott.brown@example.com', 'Indianapolis'),
('Lauren Lee', 'lauren.lee@example.com', 'Louisville'),
('Daniel Wilson', 'daniel.wilson@example.com', 'Memphis'),
('Ashley Davis', 'ashley.davis@example.com', 'St. Louis'),
('Ryan Kim', 'ryan.kim@example.com', 'Detroit');