INSERT INTO users (name, email, location, id) VALUES
('John Smith', 'john.smith@example.com', 'New York', 1),
('Jane Doe', 'jane.doe@example.com', 'Los Angeles', 2),
('Mike Johnson', 'mike.johnson@example.com', 'Chicago', 3),
('Emily Brown', 'emily.brown@example.com', 'Houston', 4),
('David Lee', 'david.lee@example.com', 'Phoenix', 5),
('Amy Wilson', 'amy.wilson@example.com', 'Philadelphia', 6),
('Brian Davis', 'brian.davis@example.com', 'San Antonio', 7),
('Lisa Thompson', 'lisa.thompson@example.com', 'San Diego', 8),
('Kevin Garcia', 'kevin.garcia@example.com', 'Dallas', 9),
('Michelle Rodriguez', 'michelle.rodriguez@example.com', 'San Jose', 10),
('Andrew Martinez', 'andrew.martinez@example.com', 'Austin', 11),
('Jessica Anderson', 'jessica.anderson@example.com', 'Jacksonville', 12),
('William Taylor', 'william.taylor@example.com', 'Fort Worth', 13),
('Melissa Hernandez', 'melissa.hernandez@example.com', 'Columbus', 14),
('Richard Moore', 'richard.moore@example.com', 'San Francisco', 15),
('Amanda Nelson', 'amanda.nelson@example.com', 'Charlotte', 16),
('Daniel Jackson', 'daniel.jackson@example.com', 'Indianapolis', 17),
('Karen White', 'karen.white@example.com', 'Seattle', 18),
('Scott Perez', 'scott.perez@example.com', 'Denver', 19),
('Julie Martin', 'julie.martin@example.com', 'Washington', 20),
('Eric Robinson', 'eric.robinson@example.com', 'Boston', 21),
('Tiffany Lewis', 'tiffany.lewis@example.com', 'Nashville', 22),
('Steven Hall', 'steven.hall@example.com', 'Baltimore', 23),
('Stephanie King', 'stephanie.king@example.com', 'Oklahoma City', 24),
('Matthew Wright', 'matthew.wright@example.com', 'Louisville', 25),
('Catherine Scott', 'catherine.scott@example.com', 'Portland', 26),
('Christopher Green', 'christopher.green@example.com', 'Las Vegas', 27),
('Rebecca Adams', 'rebecca.adams@example.com', 'Milwaukee', 28),
('Joshua Baker', 'joshua.baker@example.com', 'Albuquerque', 29),
('Nicole Mitchell', 'nicole.mitchell@example.com', 'Tucson', 30),
('Gregory Perez', 'gregory.perez@example.com', 'Fresno', 31),
('Ashley Turner', 'ashley.turner@example.com', 'Sacramento', 32),
('Bryan Cooper', 'bryan.cooper@example.com', 'Mesa', 33),
('Maria Edwards', 'maria.edwards@example.com', 'Atlanta', 34),
('Douglas Collins', 'douglas.collins@example.com', 'Kansas City', 35),
('Carolyn Ramirez', 'carolyn.ramirez@example.com', 'Miami', 36),
('Jonathan Mitchell', 'jonathan.mitchell@example.com', 'Raleigh', 37),
('Christine Peterson', 'christine.peterson@example.com', 'Omaha', 38),
('Patrick Parker', 'patrick.parker@example.com', 'Long Beach', 39),
('Lauren Ward', 'lauren.ward@example.com', 'Virginia Beach', 40),
('Ronald Turner', 'ronald.turner@example.com', 'Oakland', 41),
('Samantha Foster', 'samantha.foster@example.com', 'Minneapolis', 42),
('Peter Wright', 'peter.wright@example.com', 'Tulsa', 43),
('Katherine Cox', 'katherine.cox@example.com', 'Wichita', 44),
('Brandon Bailey', 'brandon.bailey@example.com', 'New Orleans', 45),
('Megan Barnes', 'megan.barnes@example.com', 'Tampa', 46),
('Travis Fisher', 'travis.fisher@example.com', 'Honolulu', 47),
('Hannah Henderson', 'hannah.henderson@example.com', 'Anaheim', 48),
('Ethan Collins', 'ethan.collins@example.com', 'Aurora', 49),
('Sara Ramirez', 'sara.ramirez@example.com', 'Santa Ana', 50);

select * from users;